#!/usr/local/bin/python2.7
# Start a ptrial observer and convert the data to CSV text on stdout

from ptrial.observer.core import CSV_DATA
from ptrial.observer.kernel import StorageObserver
from Queue import Queue, Empty
from threading import Thread
import time


if __name__ == '__main__':
    # TODO move to argument parsing
    output_interval = 5
    run_duration = 15
    observer_name = '{}-{}'.format('somehost', 'var')
    mount_point = '/boot'
    
    q = Queue()
    obs = StorageObserver(observer_name, q, mount_point, data_format=CSV_DATA)
    t = Thread(target=obs.run)
    t.start()
    
    for i in range(run_duration / output_interval):
        time.sleep(output_interval)
        while True:
            try:
                data = q.get(block=False)
                print data.encode('utf-8')
                q.task_done()
            except Empty:
                break
    obs.stop()
    while not q.empty():
        q.get()
        q.task_done()
    q.join()
    # complete